/**
 * coverity-common-api
 *
 * Copyright (c) 2020 Synopsys, Inc.
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.synopsys.integration.coverity.api.ws.defect;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DefectServiceService", targetNamespace = "http://ws.coverity.com/v9", wsdlLocation = "http://localhost:1780/ws/v9/defectservice?wsdl")
public class DefectServiceService
    extends Service
{

    private final static URL DEFECTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException DEFECTSERVICESERVICE_EXCEPTION;
    private final static QName DEFECTSERVICESERVICE_QNAME = new QName("http://ws.coverity.com/v9", "DefectServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1780/ws/v9/defectservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEFECTSERVICESERVICE_WSDL_LOCATION = url;
        DEFECTSERVICESERVICE_EXCEPTION = e;
    }

    public DefectServiceService() {
        super(__getWsdlLocation(), DEFECTSERVICESERVICE_QNAME);
    }

    public DefectServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEFECTSERVICESERVICE_QNAME, features);
    }

    public DefectServiceService(URL wsdlLocation) {
        super(wsdlLocation, DEFECTSERVICESERVICE_QNAME);
    }

    public DefectServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEFECTSERVICESERVICE_QNAME, features);
    }

    public DefectServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DefectServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DefectService
     */
    @WebEndpoint(name = "DefectServicePort")
    public DefectService getDefectServicePort() {
        return super.getPort(new QName("http://ws.coverity.com/v9", "DefectServicePort"), DefectService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DefectService
     */
    @WebEndpoint(name = "DefectServicePort")
    public DefectService getDefectServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.coverity.com/v9", "DefectServicePort"), DefectService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEFECTSERVICESERVICE_EXCEPTION!= null) {
            throw DEFECTSERVICESERVICE_EXCEPTION;
        }
        return DEFECTSERVICESERVICE_WSDL_LOCATION;
    }

}
