/**
 * coverity-common-api
 *
 * Copyright (c) 2019 Synopsys, Inc.
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package com.synopsys.integration.coverity.api.ws.configuration;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConfigurationService", targetNamespace = "http://ws.coverity.com/v9")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConfigurationService {


    /**
     * 
     * @param attributeDefinitionId
     * @param attributeDefinitionSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateAttribute", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateAttribute")
    @ResponseWrapper(localName = "updateAttributeResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateAttributeResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateAttributeRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateAttributeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateAttribute/Fault/CovRemoteServiceException")
    })
    public void updateAttribute(
        @WebParam(name = "attributeDefinitionId", targetNamespace = "")
        AttributeDefinitionIdDataObj attributeDefinitionId,
        @WebParam(name = "attributeDefinitionSpec", targetNamespace = "")
        AttributeDefinitionSpecDataObj attributeDefinitionSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param attributeDefinitionId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAttribute", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteAttribute")
    @ResponseWrapper(localName = "deleteAttributeResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteAttributeResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteAttributeRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteAttributeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteAttribute/Fault/CovRemoteServiceException")
    })
    public void deleteAttribute(
        @WebParam(name = "attributeDefinitionId", targetNamespace = "")
        AttributeDefinitionIdDataObj attributeDefinitionId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentMapSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createComponentMap", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateComponentMap")
    @ResponseWrapper(localName = "createComponentMapResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateComponentMapResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createComponentMapRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createComponentMapResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createComponentMap/Fault/CovRemoteServiceException")
    })
    public void createComponentMap(
        @WebParam(name = "componentMapSpec", targetNamespace = "")
        ComponentMapSpecDataObj componentMapSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentMapSpec
     * @param componentMapId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateComponentMap", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateComponentMap")
    @ResponseWrapper(localName = "updateComponentMapResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateComponentMapResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateComponentMapRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateComponentMapResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateComponentMap/Fault/CovRemoteServiceException")
    })
    public void updateComponentMap(
        @WebParam(name = "componentMapId", targetNamespace = "")
        ComponentMapIdDataObj componentMapId,
        @WebParam(name = "componentMapSpec", targetNamespace = "")
        ComponentMapSpecDataObj componentMapSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentMapId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteComponentMap", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteComponentMap")
    @ResponseWrapper(localName = "deleteComponentMapResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteComponentMapResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteComponentMapRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteComponentMapResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteComponentMap/Fault/CovRemoteServiceException")
    })
    public void deleteComponentMap(
        @WebParam(name = "componentMapId", targetNamespace = "")
        ComponentMapIdDataObj componentMapId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param groupSpec
     * @param groupId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateGroup", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateGroup")
    @ResponseWrapper(localName = "updateGroupResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateGroupResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateGroupRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateGroupResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateGroup/Fault/CovRemoteServiceException")
    })
    public void updateGroup(
        @WebParam(name = "groupId", targetNamespace = "")
        GroupIdDataObj groupId,
        @WebParam(name = "groupSpec", targetNamespace = "")
        GroupSpecDataObj groupSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param groupId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteGroup", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteGroup")
    @ResponseWrapper(localName = "deleteGroupResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteGroupResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteGroupRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteGroupResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteGroup/Fault/CovRemoteServiceException")
    })
    public void deleteGroup(
        @WebParam(name = "groupId", targetNamespace = "")
        GroupIdDataObj groupId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createProject", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateProject")
    @ResponseWrapper(localName = "createProjectResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateProjectResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createProjectRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createProjectResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createProject/Fault/CovRemoteServiceException")
    })
    public void createProject(
        @WebParam(name = "projectSpec", targetNamespace = "")
        ProjectSpecDataObj projectSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectId
     * @param projectSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateProject", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateProject")
    @ResponseWrapper(localName = "updateProjectResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateProjectResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateProjectRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateProjectResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateProject/Fault/CovRemoteServiceException")
    })
    public void updateProject(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId,
        @WebParam(name = "projectSpec", targetNamespace = "")
        ProjectSpecDataObj projectSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProject", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteProject")
    @ResponseWrapper(localName = "deleteProjectResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteProjectResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteProjectRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteProjectResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteProject/Fault/CovRemoteServiceException")
    })
    public void deleteProject(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param roleId
     * @param roleSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateRole", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateRole")
    @ResponseWrapper(localName = "updateRoleResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateRoleResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateRoleRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateRoleResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateRole/Fault/CovRemoteServiceException")
    })
    public void updateRole(
        @WebParam(name = "roleId", targetNamespace = "")
        RoleIdDataObj roleId,
        @WebParam(name = "roleSpec", targetNamespace = "")
        RoleSpecDataObj roleSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param roleId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteRole", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteRole")
    @ResponseWrapper(localName = "deleteRoleResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteRoleResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteRoleRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteRoleResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteRole/Fault/CovRemoteServiceException")
    })
    public void deleteRole(
        @WebParam(name = "roleId", targetNamespace = "")
        RoleIdDataObj roleId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createStream", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateStream")
    @ResponseWrapper(localName = "createStreamResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateStreamResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createStreamRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createStream/Fault/CovRemoteServiceException")
    })
    public void createStream(
        @WebParam(name = "streamSpec", targetNamespace = "")
        StreamSpecDataObj streamSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamSpec
     * @param streamId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateStream", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateStream")
    @ResponseWrapper(localName = "updateStreamResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateStreamResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateStreamRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateStream/Fault/CovRemoteServiceException")
    })
    public void updateStream(
        @WebParam(name = "streamId", targetNamespace = "")
        StreamIdDataObj streamId,
        @WebParam(name = "streamSpec", targetNamespace = "")
        StreamSpecDataObj streamSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamId
     * @param onlyIfEmpty
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteStream", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteStream")
    @ResponseWrapper(localName = "deleteStreamResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteStreamResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteStreamRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteStream/Fault/CovRemoteServiceException")
    })
    public void deleteStream(
        @WebParam(name = "streamId", targetNamespace = "")
        StreamIdDataObj streamId,
        @WebParam(name = "onlyIfEmpty", targetNamespace = "")
        boolean onlyIfEmpty)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param triageStoreSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createTriageStore", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateTriageStore")
    @ResponseWrapper(localName = "createTriageStoreResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateTriageStoreResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createTriageStoreRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createTriageStoreResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createTriageStore/Fault/CovRemoteServiceException")
    })
    public void createTriageStore(
        @WebParam(name = "triageStoreSpec", targetNamespace = "")
        TriageStoreSpecDataObj triageStoreSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param triageStoreId
     * @param triageStoreSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateTriageStore", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateTriageStore")
    @ResponseWrapper(localName = "updateTriageStoreResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateTriageStoreResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateTriageStoreRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateTriageStoreResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateTriageStore/Fault/CovRemoteServiceException")
    })
    public void updateTriageStore(
        @WebParam(name = "triageStoreId", targetNamespace = "")
        TriageStoreIdDataObj triageStoreId,
        @WebParam(name = "triageStoreSpec", targetNamespace = "")
        TriageStoreSpecDataObj triageStoreSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param triageStoreId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteTriageStore", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteTriageStore")
    @ResponseWrapper(localName = "deleteTriageStoreResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteTriageStoreResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteTriageStoreRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteTriageStoreResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteTriageStore/Fault/CovRemoteServiceException")
    })
    public void deleteTriageStore(
        @WebParam(name = "triageStoreId", targetNamespace = "")
        TriageStoreIdDataObj triageStoreId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param userSpec
     * @param username
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateUserResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateUserRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateUserResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateUser/Fault/CovRemoteServiceException")
    })
    public void updateUser(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "userSpec", targetNamespace = "")
        UserSpecDataObj userSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param username
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteUserResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteUserRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteUserResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteUser/Fault/CovRemoteServiceException")
    })
    public void deleteUser(
        @WebParam(name = "username", targetNamespace = "")
        String username)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.synopsys.integration.coverity.api.ws.configuration.StreamDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStreams", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetStreams")
    @ResponseWrapper(localName = "getStreamsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetStreamsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getStreamsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getStreamsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getStreams/Fault/CovRemoteServiceException")
    })
    public List<StreamDataObj> getStreams(
        @WebParam(name = "filterSpec", targetNamespace = "")
        StreamFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.ConfigurationDataObj
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSystemConfig", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetSystemConfig")
    @ResponseWrapper(localName = "getSystemConfigResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetSystemConfigResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getSystemConfigRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getSystemConfigResponse")
    public ConfigurationDataObj getSystemConfig();

    /**
     * 
     * @param username
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.UserDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetUserResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getUserRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getUserResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getUser/Fault/CovRemoteServiceException")
    })
    public UserDataObj getUser(
        @WebParam(name = "username", targetNamespace = "")
        String username)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.synopsys.integration.coverity.api.ws.configuration.ProjectDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProjects", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetProjects")
    @ResponseWrapper(localName = "getProjectsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetProjectsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getProjectsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getProjectsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getProjects/Fault/CovRemoteServiceException")
    })
    public List<ProjectDataObj> getProjects(
        @WebParam(name = "filterSpec", targetNamespace = "")
        ProjectFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.synopsys.integration.coverity.api.ws.configuration.PermissionDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPermissions", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetAllPermissions")
    @ResponseWrapper(localName = "getAllPermissionsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetAllPermissionsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getAllPermissionsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getAllPermissionsResponse")
    public List<PermissionDataObj> getAllPermissions();

    /**
     * 
     * @return
     *     returns java.util.List<com.synopsys.integration.coverity.api.ws.configuration.LdapConfigurationDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLdapConfigurations", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetAllLdapConfigurations")
    @ResponseWrapper(localName = "getAllLdapConfigurationsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetAllLdapConfigurationsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getAllLdapConfigurationsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getAllLdapConfigurationsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getAllLdapConfigurations/Fault/CovRemoteServiceException")
    })
    public List<LdapConfigurationDataObj> getAllLdapConfigurations()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param snapshotId
     * @return
     *     returns java.util.List<com.synopsys.integration.coverity.api.ws.configuration.DeleteSnapshotJobInfoDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeleteSnapshotJobInfo", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetDeleteSnapshotJobInfo")
    @ResponseWrapper(localName = "getDeleteSnapshotJobInfoResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetDeleteSnapshotJobInfoResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getDeleteSnapshotJobInfoRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getDeleteSnapshotJobInfoResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getDeleteSnapshotJobInfo/Fault/CovRemoteServiceException")
    })
    public List<DeleteSnapshotJobInfoDataObj> getDeleteSnapshotJobInfo(
        @WebParam(name = "snapshotId", targetNamespace = "")
        List<SnapshotIdDataObj> snapshotId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamId
     * @param filterSpec
     * @return
     *     returns java.util.List<com.synopsys.integration.coverity.api.ws.configuration.SnapshotIdDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSnapshotsForStream", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetSnapshotsForStream")
    @ResponseWrapper(localName = "getSnapshotsForStreamResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetSnapshotsForStreamResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotsForStreamRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotsForStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotsForStream/Fault/CovRemoteServiceException")
    })
    public List<SnapshotIdDataObj> getSnapshotsForStream(
        @WebParam(name = "streamId", targetNamespace = "")
        StreamIdDataObj streamId,
        @WebParam(name = "filterSpec", targetNamespace = "")
        SnapshotFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param serverDomainIdDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteLdapConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteLdapConfiguration")
    @ResponseWrapper(localName = "deleteLdapConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteLdapConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteLdapConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteLdapConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteLdapConfiguration/Fault/CovRemoteServiceException")
    })
    public void deleteLdapConfiguration(
        @WebParam(name = "serverDomainIdDataObj", targetNamespace = "")
        ServerDomainIdDataObj serverDomainIdDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param snapshotId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSnapshot", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteSnapshot")
    @ResponseWrapper(localName = "deleteSnapshotResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.DeleteSnapshotResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteSnapshotRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteSnapshotResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteSnapshot/Fault/CovRemoteServiceException")
    })
    public void deleteSnapshot(
        @WebParam(name = "snapshotId", targetNamespace = "")
        List<SnapshotIdDataObj> snapshotId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param acceptNewCommits
     */
    @WebMethod
    @RequestWrapper(localName = "setAcceptingNewCommits", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.SetAcceptingNewCommits")
    @ResponseWrapper(localName = "setAcceptingNewCommitsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.SetAcceptingNewCommitsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/setAcceptingNewCommitsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/setAcceptingNewCommitsResponse")
    public void setAcceptingNewCommits(
        @WebParam(name = "acceptNewCommits", targetNamespace = "")
        boolean acceptNewCommits);

    /**
     * 
     * @return
     *     returns java.util.List<com.synopsys.integration.coverity.api.ws.configuration.FeatureUpdateTimeDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastUpdateTimes", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetLastUpdateTimes")
    @ResponseWrapper(localName = "getLastUpdateTimesResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetLastUpdateTimesResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getLastUpdateTimesRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getLastUpdateTimesResponse")
    public List<FeatureUpdateTimeDataObj> getLastUpdateTimes();

    /**
     * 
     * @param viewname
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "executeNotification", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.ExecuteNotification")
    @ResponseWrapper(localName = "executeNotificationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.ExecuteNotificationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/executeNotificationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/executeNotificationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/executeNotification/Fault/CovRemoteServiceException")
    })
    public void executeNotification(
        @WebParam(name = "viewname", targetNamespace = "")
        String viewname)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectId
     * @param sourceStreamId
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.StreamDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "copyStream", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CopyStream")
    @ResponseWrapper(localName = "copyStreamResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CopyStreamResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/copyStreamRequest", output = "http://ws.coverity.com/v9/ConfigurationService/copyStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/copyStream/Fault/CovRemoteServiceException")
    })
    public StreamDataObj copyStream(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId,
        @WebParam(name = "sourceStreamId", targetNamespace = "")
        StreamIdDataObj sourceStreamId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamSpec
     * @param projectId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createStreamInProject", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateStreamInProject")
    @ResponseWrapper(localName = "createStreamInProjectResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateStreamInProjectResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createStreamInProjectRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createStreamInProjectResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createStreamInProject/Fault/CovRemoteServiceException")
    })
    public void createStreamInProject(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId,
        @WebParam(name = "streamSpec", targetNamespace = "")
        StreamSpecDataObj streamSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessageOfTheDay", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetMessageOfTheDay")
    @ResponseWrapper(localName = "getMessageOfTheDayResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetMessageOfTheDayResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getMessageOfTheDayRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getMessageOfTheDayResponse")
    public String getMessageOfTheDay();

    /**
     * 
     * @param message
     */
    @WebMethod
    @RequestWrapper(localName = "setMessageOfTheDay", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.SetMessageOfTheDay")
    @ResponseWrapper(localName = "setMessageOfTheDayResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.SetMessageOfTheDayResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/setMessageOfTheDayRequest", output = "http://ws.coverity.com/v9/ConfigurationService/setMessageOfTheDayResponse")
    public void setMessageOfTheDay(
        @WebParam(name = "message", targetNamespace = "")
        String message);

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.synopsys.integration.coverity.api.ws.configuration.ComponentMapDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComponentMaps", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetComponentMaps")
    @ResponseWrapper(localName = "getComponentMapsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetComponentMapsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getComponentMapsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getComponentMapsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getComponentMaps/Fault/CovRemoteServiceException")
    })
    public List<ComponentMapDataObj> getComponentMaps(
        @WebParam(name = "filterSpec", targetNamespace = "")
        ComponentMapFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.synopsys.integration.coverity.api.ws.configuration.TriageStoreDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTriageStores", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetTriageStores")
    @ResponseWrapper(localName = "getTriageStoresResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetTriageStoresResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getTriageStoresRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getTriageStoresResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getTriageStores/Fault/CovRemoteServiceException")
    })
    public List<TriageStoreDataObj> getTriageStores(
        @WebParam(name = "filterSpec", targetNamespace = "")
        TriageStoreFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.synopsys.integration.coverity.api.ws.configuration.LocalizedValueDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTypeNames", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetTypeNames")
    @ResponseWrapper(localName = "getTypeNamesResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetTypeNamesResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getTypeNamesRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getTypeNamesResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getTypeNames/Fault/CovRemoteServiceException")
    })
    public List<LocalizedValueDataObj> getTypeNames()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param deleteSourceStores
     * @param triageStoreId
     * @param srcTriageStoreIds
     * @param assignStreamsToTargetStore
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "mergeTriageStores", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.MergeTriageStores")
    @ResponseWrapper(localName = "mergeTriageStoresResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.MergeTriageStoresResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/mergeTriageStoresRequest", output = "http://ws.coverity.com/v9/ConfigurationService/mergeTriageStoresResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/mergeTriageStores/Fault/CovRemoteServiceException")
    })
    public void mergeTriageStores(
        @WebParam(name = "srcTriageStoreIds", targetNamespace = "")
        List<TriageStoreIdDataObj> srcTriageStoreIds,
        @WebParam(name = "triageStoreId", targetNamespace = "")
        TriageStoreIdDataObj triageStoreId,
        @WebParam(name = "deleteSourceStores", targetNamespace = "")
        boolean deleteSourceStores,
        @WebParam(name = "assignStreamsToTargetStore", targetNamespace = "")
        boolean assignStreamsToTargetStore)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDefectStatuses", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetDefectStatuses")
    @ResponseWrapper(localName = "getDefectStatusesResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetDefectStatusesResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getDefectStatusesRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getDefectStatusesResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getDefectStatuses/Fault/CovRemoteServiceException")
    })
    public List<String> getDefectStatuses()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param snapshotIds
     * @return
     *     returns java.util.List<com.synopsys.integration.coverity.api.ws.configuration.SnapshotInfoDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSnapshotInformation", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetSnapshotInformation")
    @ResponseWrapper(localName = "getSnapshotInformationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetSnapshotInformationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotInformationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotInformationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotInformation/Fault/CovRemoteServiceException")
    })
    public List<SnapshotInfoDataObj> getSnapshotInformation(
        @WebParam(name = "snapshotIds", targetNamespace = "")
        List<SnapshotIdDataObj> snapshotIds)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param snapshotId
     * @param snapshotData
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateSnapshotInfo", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateSnapshotInfo")
    @ResponseWrapper(localName = "updateSnapshotInfoResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateSnapshotInfoResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateSnapshotInfoRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateSnapshotInfoResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateSnapshotInfo/Fault/CovRemoteServiceException")
    })
    public void updateSnapshotInfo(
        @WebParam(name = "snapshotId", targetNamespace = "")
        SnapshotIdDataObj snapshotId,
        @WebParam(name = "snapshotData", targetNamespace = "")
        SnapshotInfoDataObj snapshotData)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.CommitStateDataObj
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCommitState", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetCommitState")
    @ResponseWrapper(localName = "getCommitStateResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetCommitStateResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getCommitStateRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getCommitStateResponse")
    public CommitStateDataObj getCommitState();

    /**
     * 
     * @return
     *     returns java.util.List<com.synopsys.integration.coverity.api.ws.configuration.ServerDomainIdDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLdapServerDomains", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetLdapServerDomains")
    @ResponseWrapper(localName = "getLdapServerDomainsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetLdapServerDomainsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getLdapServerDomainsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getLdapServerDomainsResponse")
    public List<ServerDomainIdDataObj> getLdapServerDomains();

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerTime", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetServerTime")
    @ResponseWrapper(localName = "getServerTimeResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetServerTimeResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getServerTimeRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getServerTimeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getServerTime/Fault/CovRemoteServiceException")
    })
    public XMLGregorianCalendar getServerTime()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.LicenseStateDataObj
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLicenseState", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetLicenseState")
    @ResponseWrapper(localName = "getLicenseStateResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetLicenseStateResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getLicenseStateRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getLicenseStateResponse")
    public LicenseStateDataObj getLicenseState();

    /**
     * 
     * @param ldapConfigurationSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createLdapConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateLdapConfiguration")
    @ResponseWrapper(localName = "createLdapConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateLdapConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createLdapConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createLdapConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createLdapConfiguration/Fault/CovRemoteServiceException")
    })
    public void createLdapConfiguration(
        @WebParam(name = "ldapConfigurationSpec", targetNamespace = "")
        LdapConfigurationSpecDataObj ldapConfigurationSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param ldapConfigurationSpec
     * @param serverDomainIdDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateLdapConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateLdapConfiguration")
    @ResponseWrapper(localName = "updateLdapConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateLdapConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateLdapConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateLdapConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateLdapConfiguration/Fault/CovRemoteServiceException")
    })
    public void updateLdapConfiguration(
        @WebParam(name = "serverDomainIdDataObj", targetNamespace = "")
        ServerDomainIdDataObj serverDomainIdDataObj,
        @WebParam(name = "ldapConfigurationSpec", targetNamespace = "")
        LdapConfigurationSpecDataObj ldapConfigurationSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.SnapshotPurgeDetailsObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSnapshotPurgeDetails", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetSnapshotPurgeDetails")
    @ResponseWrapper(localName = "getSnapshotPurgeDetailsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetSnapshotPurgeDetailsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotPurgeDetailsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotPurgeDetailsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotPurgeDetails/Fault/CovRemoteServiceException")
    })
    public SnapshotPurgeDetailsObj getSnapshotPurgeDetails()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param purgeDetailsSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setSnapshotPurgeDetails", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.SetSnapshotPurgeDetails")
    @ResponseWrapper(localName = "setSnapshotPurgeDetailsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.SetSnapshotPurgeDetailsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/setSnapshotPurgeDetailsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/setSnapshotPurgeDetailsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/setSnapshotPurgeDetails/Fault/CovRemoteServiceException")
    })
    public void setSnapshotPurgeDetails(
        @WebParam(name = "purgeDetailsSpec", targetNamespace = "")
        SnapshotPurgeDetailsObj purgeDetailsSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param licenseSpecDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "importLicense", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.ImportLicense")
    @ResponseWrapper(localName = "importLicenseResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.ImportLicenseResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/importLicenseRequest", output = "http://ws.coverity.com/v9/ConfigurationService/importLicenseResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/importLicense/Fault/CovRemoteServiceException")
    })
    public void importLicense(
        @WebParam(name = "licenseSpecDataObj", targetNamespace = "")
        LicenseSpecDataObj licenseSpecDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.LoggingConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLoggingConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetLoggingConfiguration")
    @ResponseWrapper(localName = "getLoggingConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetLoggingConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getLoggingConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getLoggingConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getLoggingConfiguration/Fault/CovRemoteServiceException")
    })
    public LoggingConfigurationDataObj getLoggingConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param loggingConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setLoggingConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.SetLoggingConfiguration")
    @ResponseWrapper(localName = "setLoggingConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.SetLoggingConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/setLoggingConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/setLoggingConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/setLoggingConfiguration/Fault/CovRemoteServiceException")
    })
    public void setLoggingConfiguration(
        @WebParam(name = "loggingConfigurationDataObj", targetNamespace = "")
        LoggingConfigurationDataObj loggingConfigurationDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.BackupConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBackupConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetBackupConfiguration")
    @ResponseWrapper(localName = "getBackupConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetBackupConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getBackupConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getBackupConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getBackupConfiguration/Fault/CovRemoteServiceException")
    })
    public BackupConfigurationDataObj getBackupConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param backupConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setBackupConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.SetBackupConfiguration")
    @ResponseWrapper(localName = "setBackupConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.SetBackupConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/setBackupConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/setBackupConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/setBackupConfiguration/Fault/CovRemoteServiceException")
    })
    public void setBackupConfiguration(
        @WebParam(name = "backupConfigurationDataObj", targetNamespace = "")
        BackupConfigurationDataObj backupConfigurationDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.SkeletonizationConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSkeletonizationConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetSkeletonizationConfiguration")
    @ResponseWrapper(localName = "getSkeletonizationConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetSkeletonizationConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getSkeletonizationConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getSkeletonizationConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getSkeletonizationConfiguration/Fault/CovRemoteServiceException")
    })
    public SkeletonizationConfigurationDataObj getSkeletonizationConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param skeletonizationConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setSkeletonizationConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.SetSkeletonizationConfiguration")
    @ResponseWrapper(localName = "setSkeletonizationConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.SetSkeletonizationConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/setSkeletonizationConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/setSkeletonizationConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/setSkeletonizationConfiguration/Fault/CovRemoteServiceException")
    })
    public void setSkeletonizationConfiguration(
        @WebParam(name = "skeletonizationConfigurationDataObj", targetNamespace = "")
        SkeletonizationConfigurationDataObj skeletonizationConfigurationDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.SignInSettingsDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSignInConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetSignInConfiguration")
    @ResponseWrapper(localName = "getSignInConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetSignInConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getSignInConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getSignInConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getSignInConfiguration/Fault/CovRemoteServiceException")
    })
    public SignInSettingsDataObj getSignInConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.synopsys.integration.coverity.api.ws.configuration.ProjectDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeveloperStreamsProjects", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetDeveloperStreamsProjects")
    @ResponseWrapper(localName = "getDeveloperStreamsProjectsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetDeveloperStreamsProjectsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getDeveloperStreamsProjectsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getDeveloperStreamsProjectsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getDeveloperStreamsProjects/Fault/CovRemoteServiceException")
    })
    public List<ProjectDataObj> getDeveloperStreamsProjects(
        @WebParam(name = "filterSpec", targetNamespace = "")
        ProjectFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.LicenseDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLicenseConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetLicenseConfiguration")
    @ResponseWrapper(localName = "getLicenseConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetLicenseConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getLicenseConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getLicenseConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getLicenseConfiguration/Fault/CovRemoteServiceException")
    })
    public LicenseDataObj getLicenseConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getArchitectureAnalysisConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetArchitectureAnalysisConfiguration")
    @ResponseWrapper(localName = "getArchitectureAnalysisConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetArchitectureAnalysisConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getArchitectureAnalysisConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getArchitectureAnalysisConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getArchitectureAnalysisConfiguration/Fault/CovRemoteServiceException")
    })
    public String getArchitectureAnalysisConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param architectureAnalysisConfiguration
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setArchitectureAnalysisConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.SetArchitectureAnalysisConfiguration")
    @ResponseWrapper(localName = "setArchitectureAnalysisConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.SetArchitectureAnalysisConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/setArchitectureAnalysisConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/setArchitectureAnalysisConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/setArchitectureAnalysisConfiguration/Fault/CovRemoteServiceException")
    })
    public void setArchitectureAnalysisConfiguration(
        @WebParam(name = "architectureAnalysisConfiguration", targetNamespace = "")
        String architectureAnalysisConfiguration)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param signInSettingsDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateSignInConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateSignInConfiguration")
    @ResponseWrapper(localName = "updateSignInConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.UpdateSignInConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateSignInConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateSignInConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateSignInConfiguration/Fault/CovRemoteServiceException")
    })
    public void updateSignInConfiguration(
        @WebParam(name = "signInSettingsDataObj", targetNamespace = "")
        SignInSettingsDataObj signInSettingsDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param fileName
     * @param snapshotId
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.OutputFileDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOutputFileForSnapshot", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetOutputFileForSnapshot")
    @ResponseWrapper(localName = "getOutputFileForSnapshotResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetOutputFileForSnapshotResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getOutputFileForSnapshotRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getOutputFileForSnapshotResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getOutputFileForSnapshot/Fault/CovRemoteServiceException")
    })
    public OutputFileDataObj getOutputFileForSnapshot(
        @WebParam(name = "snapshotId", targetNamespace = "")
        SnapshotIdDataObj snapshotId,
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCheckerNames", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetCheckerNames")
    @ResponseWrapper(localName = "getCheckerNamesResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetCheckerNamesResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getCheckerNamesRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getCheckerNamesResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getCheckerNames/Fault/CovRemoteServiceException")
    })
    public List<String> getCheckerNames()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param groupSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createGroup", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateGroup")
    @ResponseWrapper(localName = "createGroupResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateGroupResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createGroupRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createGroupResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createGroup/Fault/CovRemoteServiceException")
    })
    public void createGroup(
        @WebParam(name = "groupSpec", targetNamespace = "")
        GroupSpecDataObj groupSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param attributeDefinitionId
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.AttributeDefinitionDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAttribute", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetAttribute")
    @ResponseWrapper(localName = "getAttributeResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetAttributeResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getAttributeRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getAttributeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getAttribute/Fault/CovRemoteServiceException")
    })
    public AttributeDefinitionDataObj getAttribute(
        @WebParam(name = "attributeDefinitionId", targetNamespace = "")
        AttributeDefinitionIdDataObj attributeDefinitionId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.VersionDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetVersionResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getVersionRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getVersionResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getVersion/Fault/CovRemoteServiceException")
    })
    public VersionDataObj getVersion()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.synopsys.integration.coverity.api.ws.configuration.LocalizedValueDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCategoryNames", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetCategoryNames")
    @ResponseWrapper(localName = "getCategoryNamesResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetCategoryNamesResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getCategoryNamesRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getCategoryNamesResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getCategoryNames/Fault/CovRemoteServiceException")
    })
    public List<LocalizedValueDataObj> getCategoryNames()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param attributeDefinitionSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createAttribute", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateAttribute")
    @ResponseWrapper(localName = "createAttributeResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateAttributeResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createAttributeRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createAttributeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createAttribute/Fault/CovRemoteServiceException")
    })
    public void createAttribute(
        @WebParam(name = "attributeDefinitionSpec", targetNamespace = "")
        AttributeDefinitionSpecDataObj attributeDefinitionSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentId
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.ComponentDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComponent", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetComponent")
    @ResponseWrapper(localName = "getComponentResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetComponentResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getComponentRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getComponentResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getComponent/Fault/CovRemoteServiceException")
    })
    public ComponentDataObj getComponent(
        @WebParam(name = "componentId", targetNamespace = "")
        ComponentIdDataObj componentId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param pageSpec
     * @param filterSpec
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.GroupsPageDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroups", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetGroups")
    @ResponseWrapper(localName = "getGroupsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetGroupsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getGroupsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getGroupsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getGroups/Fault/CovRemoteServiceException")
    })
    public GroupsPageDataObj getGroups(
        @WebParam(name = "filterSpec", targetNamespace = "")
        GroupFilterSpecDataObj filterSpec,
        @WebParam(name = "pageSpec", targetNamespace = "")
        PageSpecDataObj pageSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param pageSpec
     * @param filterSpec
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.UsersPageDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetUsersResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getUsersRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getUsersResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getUsers/Fault/CovRemoteServiceException")
    })
    public UsersPageDataObj getUsers(
        @WebParam(name = "filterSpec", targetNamespace = "")
        UserFilterSpecDataObj filterSpec,
        @WebParam(name = "pageSpec", targetNamespace = "")
        PageSpecDataObj pageSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param groupId
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.GroupDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroup", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetGroup")
    @ResponseWrapper(localName = "getGroupResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetGroupResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getGroupRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getGroupResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getGroup/Fault/CovRemoteServiceException")
    })
    public GroupDataObj getGroup(
        @WebParam(name = "groupId", targetNamespace = "")
        GroupIdDataObj groupId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param roleId
     * @return
     *     returns com.synopsys.integration.coverity.api.ws.configuration.RoleDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRole", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetRole")
    @ResponseWrapper(localName = "getRoleResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetRoleResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getRoleRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getRoleResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getRole/Fault/CovRemoteServiceException")
    })
    public RoleDataObj getRole(
        @WebParam(name = "roleId", targetNamespace = "")
        RoleIdDataObj roleId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.synopsys.integration.coverity.api.ws.configuration.RoleDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllRoles", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetAllRoles")
    @ResponseWrapper(localName = "getAllRolesResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetAllRolesResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getAllRolesRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getAllRolesResponse")
    public List<RoleDataObj> getAllRoles();

    /**
     * 
     * @param roleSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createRole", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateRole")
    @ResponseWrapper(localName = "createRoleResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateRoleResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createRoleRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createRoleResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createRole/Fault/CovRemoteServiceException")
    })
    public void createRole(
        @WebParam(name = "roleSpec", targetNamespace = "")
        RoleSpecDataObj roleSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param userSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createUser", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.CreateUserResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createUserRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createUserResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createUser/Fault/CovRemoteServiceException")
    })
    public void createUser(
        @WebParam(name = "userSpec", targetNamespace = "")
        UserSpecDataObj userSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param subject
     * @param usernames
     * @param message
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "notify", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.Notify")
    @ResponseWrapper(localName = "notifyResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.NotifyResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/notifyRequest", output = "http://ws.coverity.com/v9/ConfigurationService/notifyResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/notify/Fault/CovRemoteServiceException")
    })
    public List<String> notify(
        @WebParam(name = "usernames", targetNamespace = "")
        List<String> usernames,
        @WebParam(name = "subject", targetNamespace = "")
        String subject,
        @WebParam(name = "message", targetNamespace = "")
        String message)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.synopsys.integration.coverity.api.ws.configuration.AttributeDefinitionDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAttributes", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetAttributes")
    @ResponseWrapper(localName = "getAttributesResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.synopsys.integration.coverity.api.ws.configuration.GetAttributesResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getAttributesRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getAttributesResponse")
    public List<AttributeDefinitionDataObj> getAttributes();

}
